[workspace]
resolver = "2"

members = [
    "crates/common",
    "crates/crypto",
    "crates/database",
    "crates/ffi",
    "crates/navigation",
    "crates/rendering",
    "crates/sensors",
    "crates/tracking"
]

exclude = [
    "crates/altitude",
    "crates/application",
    "crates/ar_anchor",
    "crates/domain",
    "crates/infrastructure",
    "crates/search",
    "crates/sync"
]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "1"
log = "0.4"
