[workspace]
members = [
    "crates/ffi",
    "crates/tracking",
    "crates/navigation",
    "crates/sensors",
    "crates/database",
    "crates/crypto",
    "crates/common",
    "crates/rendering"
]

resolver = "2"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "1"
log = "0.4"
