[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
application = { path = "../application" }
database = { path = "../database" }
sensors = { path = "../sensors" }
common = { path = "../common" }
ar_anchor = { path = "../ar_anchor" }
tracing.workspace = true
thiserror.workspace = true
rusqlite.workspace = true
r2d2 = "0.8"
r2d2_sqlite = "0.24"
tokio = { workspace = true, features = ["rt-multi-thread"] }
async-trait = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile = "3.10"
